apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: keycloak-postgres
  namespace: database
spec:
  teamId: "keycloak"
  volume:
    size: 10Gi
  numberOfInstances: 2
  users:
    keycloak:
    - superuser
    - createdb
  databases:
    keycloak: keycloak
  postgresql:
    version: "15"
  enableConnectionPooler: true
  enableReplicaConnectionPooler: true
  connectionPooler:
    numberOfInstances: 2
    mode: "session"
    schema: "pooler"
    user: "pooler"
    dockerImage: "registry.opensource.zalan.do/acid/pgbouncer:master-32"
    maxDBConnections: 60
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 200Mi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
