apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: keycloak-db-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - keycloak-db-secret.yaml
